### ISSUE TITLE
openssl not found

### ISSUE THREAD

**Issue by gilescope** [InvArch/INV4-Git#25]
failed to find openssl.

```
error: failed to run custom build command for `openssl-sys v0.9.75`

Caused by:
  process didn't exit successfully: `/run/user/1000/cargo-installkKDP15/release/build/openssl-sys-3208362a4ee857a6/build-script-main` (exit status: 101)
```

I suggest like other tools (eg. cargo expand) that rustls is used by default as this is much more likely to work first time.

**Comment by gilescope** [comment]
Have gone down the rabbit hole and it comes out here: https://github.com/algesten/ureq/issues/540

**Comment by arrudagates** [comment]
We actually don't need the features of the git2 crate that depend on openssl, so the solution here is just disabling them.
